### ISSUE TITLE
AttributeError: module 'custom_components.climate' has no attribute 'setup'

### ISSUE THREAD

**Issue by SaturnusDJ** [marconfus/ha-nefit-ng#12]
HA 0.90.0.

`ERROR (MainThread) [homeassistant.setup] Error during setup of component climate
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 154, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
AttributeError: module 'custom_components.climate' has no attribute 'setup'`

```
climate:
  platform: nefit
  name: Heating
  serial: 'a'
  accesskey: 'b'
  password: 'c'

logger:
  default: warn
  logs:
    custom_components.climate.nefit: debug
    aionefit: debug
```
Thermostat connected to internet. Mobile application working.

**Edit:**
🤦‍♂️ Forgot the renames. Closing issue. Likely opening a new issue for a new problem later.
Btw, had to remove the `__pycache__` directory too before it would move on.
